apiVersion: v1
kind: ConfigMap
metadata:
  name: postgis-config
  labels:
    app: postgis
data:
  POSTGRES_DB: db_tpcarto
  POSTGRES_USER: tpcarto
  POSTGRES_PASSWORD: tpcarto
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgis-deployment
spec:
  selector:
    matchLabels:
      app: postgis
  replicas: 1
  template:
    metadata:
      labels:
        app: postgis
    spec:
      containers:
      - name: postgis
        image: mdillon/postgis:12-alpine
        envFrom:
          - configMapRef:
              name: postgis-config
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgis-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgis-persistent-storage
        persistentVolumeClaim:
          claimName: postgis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgis-service
spec:
  type: NodePort
  selector:
    app: postgis
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
