apiVersion: apps/v1
kind: Deployment
metadata:
  name: rstudio-basique
  labels:
    app: rstudio-basique
    env: dev
spec:
  selector:
    matchLabels:
      app: rstudio-basique
  template:
    metadata:
      labels:
        app: rstudio-basique
    spec:
      containers:
      - name: rstudio-basique-1
        image: rocker/rstudio:latest
        env:
        - name: LOGNAME
          value: "julien"
        - name: PASSWORD
          valueFrom:
            secretKeyRef: 
              name: env-secrets
              key: PASSWORD_RSTUDIO
        - name: MC_HOST_S3
          valueFrom:
            secretKeyRef: 
              name: env-secrets
              key: MC_HOST_s3
        resources:
          limits:
            memory: "10Gi"
            cpu: "1500m"
        ports:
        - containerPort: 8787
---
apiVersion: v1
kind: Service
metadata:
  name: svc-rstudio-basique
spec:
  selector:
    app: rstudio-basique
  ports:
    - protocol: TCP
      port: 8800
      targetPort: 8787
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-rstudio-basique
spec:
  rules:
  - host: rstudio-basique.kub.sspcloud.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-rstudio-basique
            port: 
              number: 8800
