apiVersion: v1
kind: Pod
metadata:
  name: monpod
  labels:
    name: monpod
spec:
  containers:
  - name: monnginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: monvolume
  volumes:
  - name: monvolume
    hostpath:
      path: /home/onyxia/work/data/
      type: Directory
